## Numpy :

In [3]:
import numpy as np
arr = np.array([3,2,4,5])
arr

array([3, 2, 4, 5])

In [6]:
idntity = np.identity(33)
idntity
# idntity.shape

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(33, 33))

In [16]:
idntity.size# return the size 
arr2 = np.arange(45)  # arange return the array inside passing range
arr2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
arr2 = arr2.reshape((5,9)) #only given the number that multiplication = orignal array length otherwise thrown error.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [ ]:
arr2.ravel()    # becom in original position.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
import matplotlib.pyplot as plt

x = ["xrp","ogn","dot","rsr"]
y = [3,573,64,133]

plt.bar(x,y)
plt.show()
